export var READ_MENTION = "READ_MENTION";
export var CLICK_MENTION = "CLICK_MENTION";
export var RECV_MENTION = "RECV_MENTION";
export const SEND_TEXT = "SEND_TEXT";
export const RECV_TEXT = "RECV_TEXT";
export const RECV_ACCESS_TOKEN = "RECV_ACCESS_TOKEN";
export const RECV_USER_INFO = "RECV_USER_INFO";
